services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: local_sql_server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPass!123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - C:/DataAnalysis/repos/project-01-transport-expenses/data/raw:/data
    restart: unless-stopped

volumes:
  sql_data:
